image: openjdk:11-jdk-slim

stages:
  - build
  - image

build:
  stage: build
  tags:
    - docker
  script: sh ./mvnw package -B
  after_script:
    - mkdir ./docker
    - mv ./Dockerfile ./docker
    - mv ./target/*.jar ./docker
  artifacts:
    paths:
      - ./docker

build_image:
  dependencies:
    - build
  stage: image
  tags:
    - shell
  before_script:
    - docker info
    - echo "$DOCKER_REG_N1KS0_TOKEN" | docker login registry.gitlab.com -u "$DOCKER_REG_N1KS0_TOKEN" --password-stdin
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest ./docker
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  after_script:
    - docker logout registry.gitlab.com